import Navigation from '@/components/Navigation'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { IBM_Plex_Sans, Inter } from 'next/font/google'
import ThemeProvider from '@/components/ThemeProvider'
import { FooterTwo } from '@/components/FooterTwo'
import { NavigationTwo } from '@/components/NavigationTwo'

const Ibm = IBM_Plex_Sans({
  subsets: ['greek'],
  weight: ['400', '500', '700'],
  variable: '--font-Ibm'
})

const Interf = Inter({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-Inter'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${Ibm.variable} ${Interf.variable} font-Inter bg-white`}>
        <ThemeProvider>
          {/* <Navigation /> */}
          <NavigationTwo />

          <div className='max-w-4xl mx-auto mt-16 antialiased'>
            {children}
          </div>

          <FooterTwo />


        </ThemeProvider>
      </body>
    </html>
  )
}
